version: "3.8"

services:
  front:
    platform: linux/amd64
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${DOCKER_PORT}:${PORT}
    networks:
      telefactor-network:

networks:
  telefactor-network:
    external:
