import { Metadata } from "next";
import MainLayout from "./components/main-layout";

export const metadata: Metadata = {
  title: "Dashboard - Telefactor",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <MainLayout>{children}</MainLayout>;
}
